{
    'name': 'Migration Auditor',
    'version': '19.0.1.1.0',
    'summary': 'Auditoría remota de instancias Odoo y presupuesto de migraciones',
    'category': 'Technical',
    'author': 'AlejtoDev',
    'website': 'https://odoo.alejtodev.cl',
    'depends': ['base', 'web', 'mail', 'sale'],
    'data': [
        'security/auditor_security.xml',
        'security/ir.model.access.csv',
        'data/auditor_data.xml',
        'data/effort_rules_data.xml',
        'report/audit_report_action.xml',
        'report/audit_report_template.xml',
        'views/audit_category_product_views.xml',
        'views/res_config_settings_views.xml',
        'views/audit_project_views.xml',
        'views/audit_connection_views.xml',
        'views/audit_backup_views.xml',
        'views/audit_finding_views.xml',
        'views/audit_effort_line_views.xml',
        'views/wizards_views.xml',
        'views/menus.xml',
    ],
    'external_dependencies': {
        'python': ['xmlrpc.client', 'zipfile', 'psycopg2'],
    },
    'license': 'OPL-1',
    'installable': True,
    'application': True,
}
