{
    'name': 'Migration Engine',
    'version': '17.0.2.0.0',
    'summary': 'Motor ETL + inventario técnico de instancia para proyectos de migración',
    'category': 'Technical',
    'author': 'AlejtoDev',
    'website': 'https://odoo.alejtodev.cl',
    'depends': ['base', 'web'],
    'data': [
        'security/migration_security.xml',
        'security/ir.model.access.csv',
        'data/migration_data.xml',
        'views/migration_log_views.xml',
        'views/migration_execution_run_views.xml',
        'views/migration_rule_views.xml',
        'views/migration_job_views.xml',
        'views/instance_module_status_views.xml',
        'views/instance_studio_field_views.xml',
        'views/menus.xml',
    ],
    'license': 'OPL-1',
    'installable': True,
    'application': True,
}
